/**
 * Generates supabase/seed/02_starter_templates.sql from scripts/starter-templates.ts.
 * Every template is validated with the shared Zod schemas first, and stored in its
 * parsed form (defaults filled in). Run: `pnpm gen:seed`. A test fails if the
 * committed SQL is stale.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { PricingSchema, ProposalContentSchema, checkReferences, computePricing, zodIssues } from "@bridger/shared";
import { starterTemplates } from "./starter-templates.js";

export const SEED_PATH = fileURLToPath(new URL("../supabase/seed/02_starter_templates.sql", import.meta.url));

const sqlText = (s: string) => `'${s.replaceAll("'", "''")}'`;
const sqlJson = (v: unknown) => {
  const json = JSON.stringify(v);
  if (json.includes("$json$")) throw new Error("Template JSON contains the dollar-quote tag");
  return `$json$${json}$json$::jsonb`;
};

export function buildSeedSql(): string {
  const parts = [
    "-- GENERATED by scripts/gen-seed-templates.ts. Do not edit by hand; run `pnpm gen:seed`.",
    "-- Loads starter templates for every existing user (the single owner) that doesn't have them yet.",
    "-- Safe to re-run. In production, run this once after creating John's account.",
    "",
  ];
  for (const t of starterTemplates) {
    const content = ProposalContentSchema.safeParse(t.content);
    if (!content.success) throw new Error(`${t.name}: ${zodIssues(content.error, t.content).map((i) => i.message).join("; ")}`);
    const pricing = PricingSchema.safeParse(t.pricing);
    if (!pricing.success) throw new Error(`${t.name}: ${zodIssues(pricing.error).map((i) => i.message).join("; ")}`);
    const refs = checkReferences(content.data, pricing.data);
    if (refs.length) throw new Error(`${t.name}: ${refs.map((i) => i.message).join("; ")}`);
    computePricing(pricing.data); // throws on invalid defaults

    parts.push(
      `insert into public.templates (owner_id, name, description, category, content, pricing)`,
      `select u.id, ${sqlText(t.name)}, ${sqlText(t.description)}, ${sqlText(t.category)},`,
      `  ${sqlJson(content.data)},`,
      `  ${sqlJson(pricing.data)}`,
      `from auth.users u`,
      `where not exists (select 1 from public.templates x where x.owner_id = u.id and x.name = ${sqlText(t.name)});`,
      "",
    );
  }
  return parts.join("\n");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(SEED_PATH, buildSeedSql());
  console.log(`Wrote ${SEED_PATH} (${starterTemplates.length} templates)`);
}
